name_or_path: gpt2
model_cls: GPT2Editor
config_cls: GPT2EditorConfig
max_length: 512
edit_channel_multiply_factor: 2
chop_editor_at_layer: 6
num_editing_heads: 384
use_layerwise_embeddings: false
compute_position_ids: true
edit_dampening_factor: 1.0e-4
kill_token_zero: false
use_ghost_token: false
cross_attn_layers: []
restrict_edit_to_layers: []
restrict_edit_to_positions: []
target_ckpt: null